/** @file
 *
 * @brief EtherNet/IP with DHCP
 *
 * This file was generated by the Industrial Communication Creator
 * with EtherNet/IP feature on 01-29-2026.
 *
 * This application provides a simple demo for the EtherNet/IP stack.
 *
 * @copyright
 * Copyright 2025-2026 NXP
 *
 * NXP Confidential and Proprietary. This software is owned or controlled by NXP
 * and may only be used strictly in accordance with the applicable license
 * terms. By expressly accepting such terms or by downloading, installing,
 * activating and/or otherwise using the software, you are agreeing that you
 * have read, and that you agree to comply with and are bound by, such license
 * terms. If you do not agree to be bound by the applicable license terms, then
 * you may not retain, install, activate or otherwise use the software.
 *
 */


#include "goal_includes.h"
#include "goal_eip.h"
#include "goal_app_eip.h"
#include <goal_dd.h>
#if RIOP
#include "gl.h"
#endif

/**-- ICC_EIP_GEN_INCLUDES_START --**/
/* user code block */
#if RIOP
extern void riop_appl_loop(void);
static void appl_eipTxPayloadPrepare(uint8_t *pOutputData);
static void appl_eipRxPayloadProcess(uint8_t *pInputData);
#include "dce_task.h"
#endif
/**-- ICC_EIP_GEN_INCLUDES_END --**/


/****************************************************************************/
/* Local Defines */
/****************************************************************************/
/**-- ICC_EIP_GEN_DEFINE_START --**/
/* user code block */
#if RIOP
#define DEVICE_VENDOR_ID             1114       /**< vendor id */
#define DEVICE_PRODUCT_CODE          10
#endif
/**-- ICC_EIP_GEN_DEFINE_END --**/


/****************************************************************************/
/* Local Types */
/****************************************************************************/
/**-- ICC_EIP_GEN_TYPES_START --**/
/* user code block */
/**-- ICC_EIP_GEN_TYPES_END --**/


/****************************************************************************/
/* Local Prototypes */
/****************************************************************************/
GOAL_STATUS_T main_eipCallback(
    GOAL_EIP_T *pHdlEip,                        /**< EIP handle */
    GOAL_EIP_CB_ID_T id,                        /**< callback id */
    GOAL_EIP_CB_DATA_T *pCb                     /**< callback parameters */
);

static GOAL_STATUS_T main_eipIoConnectionEvent(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t outputAssembly,                    /**< output assembly connection point */
    uint32_t inputAssembly,                     /**< input assembly connection point */
    uint32_t connectionEvent                    /**< event ID */
);

static GOAL_STATUS_T main_eipAfterAssemblyDataReceived(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t instanceNr                         /**< instance number of the assembly object */
);

static GOAL_STATUS_T main_eipBeforeAssemblyDataSend(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t instanceNr                         /**< instance number of the assembly object */
);

static GOAL_STATUS_T main_eipRunIdleChanged(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t outputAssembly,                    /**< output assembly connection point */
    uint32_t inputAssembly,                     /**< input assembly connection point */
    uint32_t runIdleValue                       /**< current value of the run/idle flag */
);

static GOAL_STATUS_T main_eipAcdConflict(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint8_t dhcpEnabled,                        /**< DHCP enabled */
    uint8_t acdActivity,                        /**< ACD status */
    uint32_t acdRemoteMacHigh,                  /**< conflicted device address */
    uint16_t acdRemoteMacLow                    /**< conflicted device address */
);

static GOAL_STATUS_T main_eipResetDevice(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t resetState                         /**< type of reset */
);

/**-- ICC_EIP_GEN_LOCALPROTO_START --**/
/* user code block */
/**-- ICC_EIP_GEN_LOCALPROTO_END --**/


/****************************************************************************/
/* Local Variables */
/****************************************************************************/
/**-- ICC_EIP_GEN_LOCALVARS_START --**/
/* user code block */
#if RIOP
static uint8_t inputData[GOAL_APP_ASM_SIZE_INPUT] = {0x0};  /**< input assembly data */
static uint8_t outputData[GOAL_APP_ASM_SIZE_OUTPUT] = {0x0};  /**< output assembly data */
extern int riop_appl_init(void);
#endif
/**-- ICC_EIP_GEN_LOCALVARS_END --**/


/****************************************************************************/
/** Application
 *
 * This function initializes the CTC and GOAL.
 *
 * @retval GOAL_OK - successful
 */
GOAL_STATUS_T appl_init(
    void
)
{
    GOAL_STATUS_T res;                          /* result */

    /**-- ICC_EIP_GEN_APPLINIT_BEFORE_START --**/
    /* user code block */
    /* initialize device detection module */
    res = goal_ddInit();
    if (GOAL_RES_ERR(res)) {
	    goal_logErr("Initialization of GOAL dd failed");
	    return res;
    }
    /**-- ICC_EIP_GEN_APPLINIT_BEFORE_END --**/

    res = goal_eipInit();
    if (GOAL_RES_ERR(res)) {
       goal_logErr("Initialization of Ethernet/IP failed");
    }

    /**-- ICC_EIP_GEN_APPLINIT_AFTER_START --**/
    /* user code block */
#if RIOP
    riop_appl_init();
    dce_taskInit();
#endif
    /**-- ICC_EIP_GEN_APPLINIT_AFTER_END --**/

    return res;
}


/****************************************************************************/
/** Application Setup
 *
 * Setup the application.
 *
 * @retval GOAL_OK - successful
 */
GOAL_STATUS_T appl_setup(
    void
)
{
    GOAL_STATUS_T res;                          /* result */
    GOAL_EIP_T *pHdlEip = NULL;                 /* GOAL Ethernet/ IP handle */
    GOAL_DD_T *pHdlDd;                          /* DD handle */

    /* start goal dd with all features enabled */
    res = goal_ddNew(&pHdlDd, GOAL_DD_FEAT_ALL);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("error creating goal dd instance");
        return res;
    }

    /**-- ICC_EIP_GEN_APPLSETUP_BEFORE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_APPLSETUP_BEFORE_END --**/

    res = goal_eipCfgVendorIdSet(DEVICE_VENDOR_ID);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to set Vendor ID");
        return res;
    }

    res = goal_eipCfgProductCodeSet(DEVICE_PRODUCT_CODE);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to set Product Code");
        return res;
    }

    /* activate DHCP */
    res = goal_eipCfgDhcpOn(GOAL_TRUE);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to activate DHCP support");
        return res;
    }

    res = goal_eipCfgDlrOn(GOAL_TRUE);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to activate DLR support");
        return res;
    }

    /* activate Address Conflict Detection */
    res = goal_eipCfgAcdOn(GOAL_TRUE);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to activate ACD support");
    }

    goal_logInfo("create new instance");

    res = goal_eipNew(&pHdlEip, GOAL_ID_DEFAULT, main_eipCallback);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to create a new EtherNet/IP instance");
        return res;
    }

    /* create assembly object instances */
    /* Input Assembly */
    res = goal_eipCreateAssemblyObject(pHdlEip, GOAL_APP_ASM_ID_INPUT, GOAL_APP_ASM_SIZE_INPUT);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to create Input Assembly");
        return res;
    }

    /* Output Assembly */
    res = goal_eipCreateAssemblyObject(pHdlEip, GOAL_APP_ASM_ID_OUTPUT, GOAL_APP_ASM_SIZE_OUTPUT);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to create Output Assembly");
        return res;
    }

    /* Config Assembly */
    res = goal_eipCreateAssemblyObject(pHdlEip, GOAL_APP_ASM_ID_CONFIG, GOAL_APP_ASM_SIZE_CONFIG);
    if (GOAL_RES_ERR(res)) {
        goal_logErr("failed to create Config Assembly");
        return res;
    }


    /* define allowed connections */
    if (GOAL_RES_OK(res)) {
        res = goal_eipAddExclusiveOwnerConnection(pHdlEip,
                                            GOAL_APP_ASM_ID_OUTPUT,
                                            GOAL_APP_ASM_ID_INPUT,
                                            GOAL_APP_ASM_ID_CONFIG);
    }

    if (GOAL_RES_OK(res)) {
        res = goal_eipAddInputOnlyConnection(pHdlEip,
                                            GOAL_APP_IOCON_NUM,
                                            GOAL_APP_ASM_ID_HEARTBEAT_IO,
                                            GOAL_APP_ASM_ID_INPUT,
                                            GOAL_APP_ASM_ID_CONFIG);
    }

    if (GOAL_RES_OK(res)) {
        res = goal_eipAddListenOnlyConnection(pHdlEip,
                                            GOAL_APP_LOCON_NUM,
                                            GOAL_APP_ASM_ID_HEARTBEAT_LO,
                                            GOAL_APP_ASM_ID_INPUT,
                                            GOAL_APP_ASM_ID_CONFIG);
    }
    /**-- ICC_EIP_GEN_APPLSETUP_AFTER_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_APPLSETUP_AFTER_END --**/

    return GOAL_OK;
}


/****************************************************************************/
/** Inform the application on changes occurred for a connection
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
static GOAL_STATUS_T main_eipIoConnectionEvent(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t pa_unOutputAssembly,               /**< output assembly connection point */
    uint32_t pa_unInputAssembly,                /**< input assembly connection point */
    uint32_t pa_eIOConnectionEvent              /**< event ID */
)
{
    UNUSEDARG(pHdlEip);
    UNUSEDARG(pa_unOutputAssembly);
    UNUSEDARG(pa_unInputAssembly);

    /**-- ICC_EIP_GEN_IOCONNECTIONEVENT_BEFORE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_IOCONNECTIONEVENT_BEFORE_END --**/

    /* react to  connection events
     * - connection opened
     * - connection closed
     * - connection timed out
     */
    switch (pa_eIOConnectionEvent) {
        case GOAL_EIP_CONNECTION_EVENT_OPENED:
            /**-- ICC_EIP_GEN_EVENT_OPENED_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_EVNET_OPENED_END --**/

            break;
        case GOAL_EIP_CONNECTION_EVENT_CLOSED:
            /**-- ICC_EIP_GEN_EVENT_CLOSED_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_EVENT_CLOSED_END --**/

            break;
        case GOAL_EIP_CONNECTION_EVENT_TIMEOUT:
            /**-- ICC_EIP_GEN_EVENT_TIMEOUT_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_EVENT_TIMEOUT_END --**/

            break;
        default:
           break;
    }

    /**-- ICC_EIP_GEN_IOCONNECTIONEVENT_AFTER_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_IOCONNECTIONEVENT_BEFORE_END --**/

     return GOAL_OK;
}


/****************************************************************************/
/** Call back function to inform application on received data for an assembly object
 *
 * This function has to be implemented by the user of the CIP-stack.
 * Assembly Objects for Configuration Data:
 * The CIP-stack uses this function to inform on received configuration data. The length of the data
 * is already checked within the stack. Therefore the user only has to check if the data is valid.
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
static GOAL_STATUS_T main_eipAfterAssemblyDataReceived(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t instanceNr                         /**< instance number of the assembly object */
)
{
    UNUSEDARG(pHdlEip);
    GOAL_STATUS_T res = GOAL_OK;

    /**-- ICC_EIP_GEN_AFTER_ASSEMBLYDATA_REC_BEFORE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_AFTER_ASSEMBLYDATA_REC_BEFORE_END --**/

    /* check which Assembly Object has new data */
    switch (instanceNr) {
        case GOAL_APP_ASM_ID_INPUT:
            /**-- ICC_EIP_GEN_ASM_ID_INPUT_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_ASM_ID_INPUT_END --**/

            break;

        case GOAL_APP_ASM_ID_OUTPUT:
            /**-- ICC_EIP_GEN_ASM_ID_OUTPUT_START --**/
            /* user code block */
#if RIOP
            res = goal_eipAssemblyObjectRead(pHdlEip, GOAL_APP_ASM_ID_OUTPUT, &outputData[0], GOAL_APP_ASM_SIZE_OUTPUT);
            if (GOAL_RES_OK(res)) {
		appl_eipRxPayloadProcess (&outputData[0]);
            }
#endif
            /**-- ICC_EIP_GEN_ASM_ID_OUTPUT_END --**/

            break;

        case GOAL_APP_ASM_ID_CONFIG:
            /**-- ICC_EIP_GEN_ASM_ID_CONFIG_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_ASM_ID_CONFIG_END --**/

            break;

        case GOAL_APP_ASM_ID_HEARTBEAT_IO:
            /**-- ICC_EIP_GEN_ASM_ID_HB_IO_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_ASM_ID_HB_IO_END --**/

            break;

        case GOAL_APP_ASM_ID_HEARTBEAT_LO:
            /**-- ICC_EIP_GEN_ASM_ID_HB_LO_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_ASM_ID_HB_LO_END --**/

            break;

        default:
            goal_logErr("Unknown instance ID %"FMT_u32, instanceNr);
            res = GOAL_ERR_EIP;
            /**-- ICC_EIP_GEN_ASM_ID_DEFAULT_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_ASM_ID_DEFAULT_END --**/

            return res;
    }

    /**-- ICC_EIP_GEN_AFTER_ASSEMBLYDATA_REC_AFTER_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_AFTER_ASSEMBLYDATA_REC_BEFORE_END --**/

    return res;
}


/****************************************************************************/
/** Inform the application that the data of an assembly object will be sent.
 *
 * Within this function the user can update the data of the assembly object
 * before it gets sent. The application can inform the stack if data has changed.
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
static GOAL_STATUS_T main_eipBeforeAssemblyDataSend(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t instanceNr                         /**< instance number of the assembly object */
)
{
    GOAL_STATUS_T res = GOAL_OK;                /* result */

    UNUSEDARG(pHdlEip);

    /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_BEFORE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_BEFORE_END --**/

    switch (instanceNr) {
        /* example Code
         *
         * case GOAL_APP_ASM_ID_INPUT:
         * get output data
         * res = goal_eipAssemblyObjectRead(pHdlEip, GOAL_APP_ASM_ID_OUTPUT, &outputData[0], GOAL_APP_ASM_SIZE_OUTPUT);

         * mirror output data to input data
         *  if (GOAL_RES_OK(res)) {
         *      GOAL_MEMCPY(&inputData[0], &outputData[0], GOAL_APP_ASM_SIZE_INPUT);
         *  }

         * store input data
         *  if (GOAL_RES_OK(res)) {
         *      res = goal_eipAssemblyObjectWrite(pHdlEip, GOAL_APP_ASM_ID_INPUT, &inputData[0], GOAL_APP_ASM_SIZE_INPUT);
         *  }
         *  break;
         */
        /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_SWITCH_START --**/
        /* user code block */
#if RIOP
         case GOAL_APP_ASM_ID_INPUT:
		appl_eipTxPayloadPrepare (&inputData[0]);
            	res = goal_eipAssemblyObjectWrite(pHdlEip, GOAL_APP_ASM_ID_INPUT, &inputData[0], GOAL_APP_ASM_SIZE_INPUT);
#endif
        /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_SWITCH_END --**/

        default:
            goal_logErr("Unknown instance ID %"FMT_u32, instanceNr);
            res = GOAL_ERR_EIP;

           /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_SWITCHDEF_START --**/
            /* user code block */
           /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_SWITCHDEF_END --**/

      break;
    }

    /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_AFTER_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_BEFORE_ASSEMBLYDATA_SEND_AFTER_END --**/

    return res;
}


/****************************************************************************/
/** Inform the application that the Run/Idle State has been changed by the originator.
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
static GOAL_STATUS_T main_eipRunIdleChanged(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t outputAssembly,                    /**< output assembly connection point */
    uint32_t inputAssembly,                     /**< input assembly connection point */
    uint32_t runIdleValue                       /**< current value of the run/idle flag */
)
{
    UNUSEDARG(pHdlEip);
    UNUSEDARG(runIdleValue);
    UNUSEDARG(outputAssembly);
    UNUSEDARG(inputAssembly);

    GOAL_STATUS_T res = GOAL_OK;

    /* example code
     *
     * if ((GOAL_APP_ASM_ID_OUTPUT == outputAssembly) &&
     *  (GOAL_APP_ASM_ID_INPUT == inputAssembly)) {
     *  goal_logInfo("runIdleHeader changed for exclusive owner connection: %"FMT_u32,
     *               runIdleValue);
     * }
     */
    /**-- ICC_EIP_GEN_RUN_IDLE_CHANGED_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_RUN_IDLE_CHANGED_END --**/

    return res;
}


/****************************************************************************/
/** Inform Application that device will be reset
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
static GOAL_STATUS_T main_eipResetDevice(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint32_t resetState                         /**< type of reset */
)
{
    UNUSEDARG(pHdlEip);
    UNUSEDARG(resetState);

    GOAL_STATUS_T res = GOAL_OK;

    goal_logInfo("device is reset: %s", (GOAL_EIP_RESET_POWER == resetState) ? "Power Cycle"
                                       : (GOAL_EIP_RESET_FACTORY == resetState) ? "Factory Reset"
                                       : (GOAL_EIP_RESET_FACTORY_COMM == resetState) ? "Factory Reset (no Com)"
                                       : "unknown");

    /**-- ICC_EIP_GEN_RESET_DEVICE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_RESET_DEVICE_END --**/

    return res;
}


/****************************************************************************/
/** EtherNet/IP Callback Handler
 *
 * This function collects all callbacks from the stack and decides if the
 * callback must be handled.
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
GOAL_STATUS_T main_eipCallback(
    GOAL_EIP_T *pHdlEip,                        /**< PROFINET handle */
    GOAL_EIP_CB_ID_T id,                        /**< callback id */
    GOAL_EIP_CB_DATA_T *pCb                     /**< callback parameters */
)
{
    GOAL_STATUS_T res = GOAL_OK;                /* return value */

    /**-- ICC_EIP_GEN_EIPCALLBACK_BEFORE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_EIPCALLBACK_BEFORE_END --**/

    /* handle callback IDs */
    switch (id) {

#if !RIOP
        case GOAL_EIP_CB_ID_INIT:
            break;
#endif

        case GOAL_EIP_CB_ID_READY:
            /* inform the application about object creation done */
            break;

        case GOAL_EIP_CB_ID_CONNECT_EVENT:
            /* inform the application on changes occurred for a connection */
            res = main_eipIoConnectionEvent(
                pHdlEip,
                pCb->data[0].outputAssembly,
                pCb->data[1].inputAssembly,
                pCb->data[2].connectionEvent);
            break;

        case GOAL_EIP_CB_ID_RUN_IDLE_CHANGED:
            /* inform the application on Run/Idle State changed by the originator */
            res = main_eipRunIdleChanged(
                pHdlEip,
                pCb->data[0].outputAssembly,
                pCb->data[1].inputAssembly,
                pCb->data[2].runIdleValue);
            break;

        case GOAL_EIP_CB_ID_ASSEMBLY_DATA_SEND:
            /* Inform the application about assembly object being sent next */
            res = main_eipBeforeAssemblyDataSend(
                pHdlEip,
                pCb->data[0].instanceNr);
            break;

        case GOAL_EIP_CB_ID_ASSEMBLY_DATA_RECV:
            /* inform application on received data for an assembly object */
            res = main_eipAfterAssemblyDataReceived(
                pHdlEip,
                pCb->data[0].instanceNr);
            break;

        case GOAL_EIP_CB_ID_DEVICE_RESET:
            /* inform Application that device will be reset */
            res = main_eipResetDevice(
                pHdlEip,
                pCb->data[0].resetState);
            break;

        case GOAL_EIP_CB_ID_ACD_CONFLICT:
            /* Inform Application about a detected address conflict.
             * If a conflict behavior is configured, the device will
             * try to solve the conflict. Otherwise the device stays
             * in a mayor unrecoverable fault. If the return-value is
             * GOAL_ERROR, the device will also transit into a mayor
             * unrecoverable fault.
             */
            res = main_eipAcdConflict(
                pHdlEip,
                pCb->data[0].dhcpEnabled,
                pCb->data[1].acdActivity,
                pCb->data[2].acdRemoteMacHigh,
                pCb->data[3].acdRemoteMacLow);
            break;

        default:
            /**-- ICC_EIP_GEN_EIPCALLBACK_DEFAULT_START --**/
            /* user code block */
            /**-- ICC_EIP_GEN_EIPCALLBACK_DEFAULT_END --**/

            break;
    }

    /**-- ICC_EIP_GEN_EIPCALLBACK_AFTER_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_EIPCALLBACK_AFTER_END --**/

    return res;
}


/****************************************************************************/
/** Inform Application about detected address conflict
 *
 * @retval GOAL_OK successful
 * @retval other failed
 */
static GOAL_STATUS_T main_eipAcdConflict(
    GOAL_EIP_T *pHdlEip,                        /**< GOAL Ethernet/ IP handle */
    uint8_t dhcpEnabled,                        /**< DHCP enabled */
    uint8_t acdActivity,                        /**< ACD status */
    uint32_t acdRemoteMacHigh,                  /**< conflicted device address */
    uint16_t acdRemoteMacLow                    /**< conflicted device address */
)
{
    GOAL_STATUS_T res;                          /* result */
    GOAL_ACD_LAST_CONFLICT_DETECTED_T attribute; /* ACD attribute */
    uint8_t acdRemoteMac[MAC_ADDR_LEN];         /* remote MAC */

    UNUSEDARG(dhcpEnabled);
    UNUSEDARG(acdActivity);

    /**-- ICC_EIP_GEN_ACDCONFLICT_BEFORE_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_ACDCONFLICT_BEFORE_END --**/

    /* copy received MAC into array */
    GOAL_MEMCPY(&acdRemoteMac, &acdRemoteMacHigh, sizeof(acdRemoteMacHigh));
    GOAL_MEMCPY(&acdRemoteMac[4], &acdRemoteMacLow, sizeof(acdRemoteMacLow));

    goal_logInfo("address conflict caused by device %02x:%02x:%02x:%02x:%02x:%02x",
            acdRemoteMac[0],
            acdRemoteMac[1],
            acdRemoteMac[2],
            acdRemoteMac[3],
            acdRemoteMac[4],
            acdRemoteMac[5]);

    /* get whole ACD attribute */
    res = goal_eipAcdLastConflictDetectedGet(pHdlEip, &attribute);
    if (GOAL_RES_OK(res)) {
        /* log information of attribute */
        goal_logInfo("stop using IP address %d.%d.%d.%d, get new IP after timeout",
                attribute.arpPru.targetProtodAdress[0],
                attribute.arpPru.targetProtodAdress[1],
                attribute.arpPru.targetProtodAdress[2],
                attribute.arpPru.targetProtodAdress[3]);
    }

    res = GOAL_ERROR;

    /**-- ICC_EIP_GEN_ACDCONFLICT_AFTER_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_ACDCONFLICT_AFTER_END --**/

    return res;

}

#if 0
/****************************************************************************/
/** Application Loop
 *
 * This function must implement the application logic and must not block. It is
 * called in a loop (the GOAL loop) and if state tracking is necessary it
 * should use static or global variables.
 */
void appl_loop(
    void
)
{
    /**-- ICC_EIP_GEN_APPLLOOP_START --**/
    /* user code block */
    /**-- ICC_EIP_GEN_APPLLOOP_END --**/

}
#endif

#if RIOP
/* packed structure for riop input data */
typedef struct __attribute__((packed)) {
    uint8_t di1_in;
    uint8_t di2_in;
    uint8_t di3_in;
    uint8_t di4_in;
    uint8_t di5_in;
    uint8_t di6_in;
    uint8_t di7_in;
    uint8_t di8_in;
    uint8_t di9_in;
    uint8_t di10_in;
    uint8_t di11_in;
    uint8_t di12_in;
    uint8_t di13_in;
    uint8_t di14_in;
    uint8_t di15_in;
    uint8_t di16_in;
    uint8_t di17_in;
    uint8_t di18_in;
    uint8_t di19_in;
    uint8_t di20_in;
    uint8_t di21_in;
    uint8_t di22_in;
    uint8_t di23_in;
    uint8_t di24_in;
    uint8_t di25_in;
    uint8_t di26_in;
    uint8_t di27_in;
    uint8_t di28_in;
    uint8_t di29_in;
    uint8_t di30_in;
    uint8_t di31_in;
    uint8_t di32_in;
    uint8_t led_in;
    uint32_t adc1_in;
    uint32_t adc2_in;
    int32_t adc3_in;
    int32_t adc4_in;
    float adc5_in;
    float adc6_in;
    float adc7_in;
    float adc8_in;
    float adc9_in;
    float adc10_in;
    float adc11_in;
    float adc12_in;
    float adc13_in;
    float adc14_in;
    float adc15_in;
    float adc16_in;
} riop_data_in;

/* packed structure for riop output data */
typedef struct __attribute__((packed)) {
    uint8_t di1_out;
    uint8_t di2_out;
    uint8_t di3_out;
    uint8_t di4_out;
    uint8_t di5_out;
    uint8_t di6_out;
    uint8_t di7_out;
    uint8_t di8_out;
    uint8_t di9_out;
    uint8_t di10_out;
    uint8_t di11_out;
    uint8_t di12_out;
    uint8_t di13_out;
    uint8_t di14_out;
    uint8_t di15_out;
    uint8_t di16_out;
    uint8_t di17_out;
    uint8_t di18_out;
    uint8_t di19_out;
    uint8_t di20_out;
    uint8_t di21_out;
    uint8_t di22_out;
    uint8_t di23_out;
    uint8_t di24_out;
    uint8_t di25_out;
    uint8_t di26_out;
    uint8_t di27_out;
    uint8_t di28_out;
    uint8_t di29_out;
    uint8_t di30_out;
    uint8_t di31_out;
    uint8_t di32_out;
    uint8_t led_out;
    uint32_t adc1_out;
    uint32_t adc2_out;
    int32_t adc3_out;
    int32_t adc4_out;
    float adc5_out;
    float adc6_out;
    float adc7_out;
    float adc8_out;
    float adc9_out;
    float adc10_out;
    float adc11_out;
    float adc12_out;
    float adc13_out;
    float adc14_out;
    float adc15_out;
    float adc16_out;
} riop_data_out;

/****************************************************************************/
/** Process the ethernet-ip rx payload (output data) received from PLC
 *
 */
static void appl_eipRxPayloadProcess(
	uint8_t *pOutputData
)
{
    /* Copy data from master to slave*/
        uint16_t * pi;
        uint8_t * pii;
        pi=&riop_command.afe_command.afe_gpio_command.gpio_output_value;
	riop_data_in * pData = (riop_data_in *)pOutputData;

#define ATOMIC_OP(var, XXX) if(pData->var) *pi|=(uint16_t)XXX; else *pi&=~(uint16_t)XXX
        ATOMIC_OP(di1_in, 0x0004);
        ATOMIC_OP(di2_in, 0x0008);
        ATOMIC_OP(di3_in, 0x0010);
        ATOMIC_OP(di4_in, 0x0020);

        ATOMIC_OP(di5_in, 0x0040);
        ATOMIC_OP(di6_in, 0x0080);
        ATOMIC_OP(di7_in, 0x0100);
        ATOMIC_OP(di8_in, 0x0200);
#undef ATOMIC_OP

#define ATOMIC_OP(var, XXX) if(pData->var) *pii|=(uint8_t)XXX; else *pii&=~(uint8_t)XXX
        pii=&riop_command.mcu_digital_output_command.mcu_digital_output;
        ATOMIC_OP(di17_in, 0x01);
        ATOMIC_OP(di18_in, 0x02);
        ATOMIC_OP(di19_in, 0x04);
        ATOMIC_OP(di20_in, 0x08);

        ATOMIC_OP(di21_in, 0x10);
        ATOMIC_OP(di22_in, 0x20);
        ATOMIC_OP(di23_in, 0x40);
        ATOMIC_OP(di24_in, 0x80);
#undef ATOMIC_OP

#define ATOMIC_OP(var, XXX) if(pData->var) riop_command.afe_command.afe_gpio_command.gpio_pin_direction |=XXX; \
                else riop_command.afe_command.afe_gpio_command.gpio_pin_direction &=~(uint16_t)XXX;

        ATOMIC_OP(di25_in, 0x0004);
        ATOMIC_OP(di26_in, 0x0008);
        ATOMIC_OP(di27_in, 0x0010);
        ATOMIC_OP(di28_in, 0x0020);
        ATOMIC_OP(di29_in, 0x0040);
        ATOMIC_OP(di30_in, 0x0080);
        ATOMIC_OP(di31_in, 0x0100);
        ATOMIC_OP(di32_in, 0x0200);
#undef ATOMIC_OP

        //Mostly unused analog outputs.
        GOAL_MEMCPY(&LED_status,&pData->led_in,sizeof(LED_status));
        {
                uint32_t tt;
                GOAL_MEMCPY( &fsm_mode, &pData->adc1_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc2_in, sizeof(tt));
        }
        led_green = LED_status;

        {
                int32_t tt;
                GOAL_MEMCPY( &tt, &pData->adc3_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc4_in, sizeof(tt));
        }
        {
                float tt;
                tt=0.0;
                GOAL_MEMCPY( &tt, &pData->adc5_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc6_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc7_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc8_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc9_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc10_in, sizeof(tt));

                GOAL_MEMCPY( &tt, &pData->adc11_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc12_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc13_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc14_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc15_in, sizeof(tt));
                GOAL_MEMCPY( &tt, &pData->adc16_in, sizeof(tt));
        }
        
}

/****************************************************************************/
/** Prepare ethernet-ip tx data that will be sent (inputs) to PLC
 *
 */
static void appl_eipTxPayloadPrepare(
	uint8_t *pInputData
)
{
        uint8_t di;
        di=0;
        uint16_t * pi;
        uint8_t * pii;
        pi=&g_boardStatus.afe_status.afe_gpio_input_pins_status;
	riop_data_out * pData = (riop_data_out *)pInputData;

#define ATOMIC_OP(var, XXX) if(*pi&(uint16_t)XXX) pData->var=1; else pData->var=0
        ATOMIC_OP(di1_out, 0x0004);
        ATOMIC_OP(di2_out, 0x0008);
        ATOMIC_OP(di3_out, 0x0010);
        ATOMIC_OP(di4_out, 0x0020);

        ATOMIC_OP(di5_out, 0x0040);
        ATOMIC_OP(di6_out, 0x0080);
        ATOMIC_OP(di7_out, 0x0100);
        ATOMIC_OP(di8_out, 0x0200);
#undef ATOMIC_OP

#define ATOMIC_OP(var, XXX) if(*pii&(uint8_t)XXX) pData->var=1; else pData->var=0
        pii=&g_boardStatus.mcu_digital_input_pins_status;
        ATOMIC_OP(di9_out, 0x01);
        ATOMIC_OP(di10_out, 0x02);
        ATOMIC_OP(di11_out, 0x04);
        ATOMIC_OP(di12_out, 0x08);

        ATOMIC_OP(di13_out, 0x10);
        ATOMIC_OP(di14_out, 0x20);
        ATOMIC_OP(di15_out, 0x40);
        GOAL_MEMCPY(&pData->di16_out, &di, sizeof(di));

        pii=&g_boardStatus.mcu_digital_output_pins_status;
        ATOMIC_OP(di17_out, 0x01);
        ATOMIC_OP(di18_out, 0x02);
        ATOMIC_OP(di19_out, 0x04);
        ATOMIC_OP(di20_out, 0x08);

        ATOMIC_OP(di21_out, 0x10);
        ATOMIC_OP(di22_out, 0x20);
        ATOMIC_OP(di23_out, 0x40);
        ATOMIC_OP(di24_out, 0x80);

#undef ATOMIC_OP
	//NA di25-32
        
	//LED
        GOAL_MEMCPY(&pData->led_out,&LED_status,sizeof(LED_status));
        {
                uint32_t tt;
                tt=(adc_1);
                GOAL_MEMCPY(&pData->adc1_out, &tt, sizeof(tt));
                GOAL_MEMCPY(&pData->adc2_out, &adc_1, sizeof(adc_1));
        }
        {
                int32_t tt;
                tt=(adc_1);
                tt=-tt;
                GOAL_MEMCPY(&pData->adc3_out, &tt, sizeof(tt));
                GOAL_MEMCPY(&pData->adc4_out, &tt, sizeof(tt));
        }
        {
                float * pf;
                float tt;
                tt=(adc_1);
                pf=&(g_boardStatus.afe_status.hvsig_status.channel_value[0]);
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc5_out, &tt, sizeof(tt));
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc6_out, &tt, sizeof(tt));
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc7_out, &tt, sizeof(tt));
                pf=&(g_boardStatus.afe_status.current_status.channel_value);
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc8_out, &tt, sizeof(tt));
                pf=&(g_boardStatus.afe_status.lvsig_status.channel_mean[0]);
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc9_out, &tt, sizeof(tt));
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc10_out, &tt, sizeof(tt));
                tt=*pf++;

                GOAL_MEMCPY(&pData->adc11_out, &tt, sizeof(tt));
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc12_out, &tt, sizeof(tt));
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc13_out, &tt, sizeof(tt)); //#13

                pf=&(g_boardStatus.afe_status.temperature_status.channel_value);
                tt=*pf++;
                GOAL_MEMCPY(&pData->adc14_out, &tt, sizeof(tt)); //#14
                GOAL_MEMCPY(&pData->adc15_out, &tt, sizeof(tt)); //#15
                GOAL_MEMCPY(&pData->adc16_out, &tt, sizeof(tt)); //#16
        }

        /* CentriFeeder: publish DCE FlowRate / Totalization over the former
         * temperature-duplicate float slots adc15_out / adc16_out. Overrides
         * the temperature values written just above. */
        {
                DCE_DATA_T dce;
                dce_dataGet(&dce);
                GOAL_MEMCPY(&pData->adc15_out, &dce.flowRate,     sizeof(float)); //FlowRate
                GOAL_MEMCPY(&pData->adc16_out, &dce.totalization, sizeof(float)); //Totalization
        }
}
#endif
