/** @file
 *
 * @brief
 * CIP Parameter Instance Table
 *
 * @details
 * This module contains the instance attributes of all Parameter Objects. The
 * attributes are organized in a table.
 *
 * This file was generated by the Industrial Communication Creator
 * with EtherNet/IP feature on 11-17-2025.
 *
 * @copyright
 * Copyright 2010-2019 port GmbH Halle/Saale.
 * This software is protected Intellectual Property and may only be used
 * according to the license agreement.
 *
 * Copyright 2025 NXP
 *
 * NXP Confidential and Proprietary. This software is owned or controlled by NXP
 * and may only be used strictly in accordance with the applicable license
 * terms. By expressly accepting such terms or by downloading, installing,
 * activating and/or otherwise using the software, you are agreeing that you
 * have read, and that you agree to comply with and are bound by, such license
 * terms. If you do not agree to be bound by the applicable license terms, then
 * you may not retain, install, activate or otherwise use the software.
 */


#ifndef APP_PARAMETER_DATA_H
#define APP_PARAMETER_DATA_H


/****************************************************************************/
/* Parameter Values (current value, default value, limits) */
/****************************************************************************/


/****************************************************************************/
/* Parameter Table */
/****************************************************************************/
static GOAL_EIP_PARAM_TABLE_ENTRY_T paramTable[] = {
/* instance, access,                  data type,                       value,                 min,                     max,                   defVal,                 name,               help string */

};

#endif /* APP_PARAMETER_DATA_H */
