/*
 * Copyright 2024-2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AON_19 (coord D5), LPUART1_CTS */
/* Routed pin properties */
#define LPUART1_CTS_PERIPHERAL                                           LPUART1   /*!< Peripheral name */
#define LPUART1_CTS_SIGNAL                                                 CTS_B   /*!< Signal name */

/* GPIO_AON_20 (coord E5), LPUART1_RTS */
/* Routed pin properties */
#define LPUART1_RTS_PERIPHERAL                                           LPUART1   /*!< Peripheral name */
#define LPUART1_RTS_SIGNAL                                                 RTS_B   /*!< Signal name */

/* GPIO_AON_08 (coord B1), LPUART1_TX */
/* Routed pin properties */
#define LPUART1_TX_PERIPHERAL                                            LPUART1   /*!< Peripheral name */
#define LPUART1_TX_SIGNAL                                                    TXD   /*!< Signal name */

/* GPIO_AON_09 (coord A5), LPUART1_RX */
/* Routed pin properties */
#define LPUART1_RX_PERIPHERAL                                            LPUART1   /*!< Peripheral name */
#define LPUART1_RX_SIGNAL                                                    RXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_LPUART1_RS485_Pins(void);     /* Function assigned for the Cortex-M33 */

/* GPIO_EMC_B2_17 (coord U7), RXD0 */
/* Routed pin properties */
#define NETC_ENETC0_RXD0_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_RXD0_SIGNAL                                          RX_DATA   /*!< Signal name */
#define NETC_ENETC0_RXD0_CHANNEL                                              0U   /*!< Signal channel */

/* GPIO_EMC_B2_18 (coord P8), RXD1 */
/* Routed pin properties */
#define NETC_ENETC0_RXD1_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_RXD1_SIGNAL                                          RX_DATA   /*!< Signal name */
#define NETC_ENETC0_RXD1_CHANNEL                                              1U   /*!< Signal channel */

/* GPIO_EMC_B2_10 (coord U6), RXD2 */
/* Routed pin properties */
#define NETC_ENETC0_RXD2_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_RXD2_SIGNAL                                          RX_DATA   /*!< Signal name */
#define NETC_ENETC0_RXD2_CHANNEL                                              2U   /*!< Signal channel */

/* GPIO_EMC_B2_09 (coord U5), RXD3 */
/* Routed pin properties */
#define NETC_ENETC0_RXD3_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_RXD3_SIGNAL                                          RX_DATA   /*!< Signal name */
#define NETC_ENETC0_RXD3_CHANNEL                                              3U   /*!< Signal channel */

/* GPIO_EMC_B2_19 (coord U8), RXEN */
/* Routed pin properties */
#define NETC_ENETC0_RXEN_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_RXEN_SIGNAL                                            RX_EN   /*!< Signal name */

/* GPIO_EMC_B2_08 (coord U4), RXCLK */
/* Routed pin properties */
#define NETC_ENETC0_RXCLK_PERIPHERAL                            NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_RXCLK_SIGNAL                                          RX_CLK   /*!< Signal name */

/* GPIO_EMC_B2_13 (coord R6), TXD0 */
/* Routed pin properties */
#define NETC_ENETC0_TXD0_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_TXD0_SIGNAL                                          TX_DATA   /*!< Signal name */
#define NETC_ENETC0_TXD0_CHANNEL                                              0U   /*!< Signal channel */

/* GPIO_EMC_B2_14 (coord N8), TXD1 */
/* Routed pin properties */
#define NETC_ENETC0_TXD1_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_TXD1_SIGNAL                                          TX_DATA   /*!< Signal name */
#define NETC_ENETC0_TXD1_CHANNEL                                              1U   /*!< Signal channel */

/* GPIO_EMC_B2_12 (coord R5), TXD2 */
/* Routed pin properties */
#define NETC_ENETC0_TXD2_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_TXD2_SIGNAL                                          TX_DATA   /*!< Signal name */
#define NETC_ENETC0_TXD2_CHANNEL                                              2U   /*!< Signal channel */

/* GPIO_EMC_B2_11 (coord P6), TXD3 */
/* Routed pin properties */
#define NETC_ENETC0_TXD3_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_TXD3_SIGNAL                                          TX_DATA   /*!< Signal name */
#define NETC_ENETC0_TXD3_CHANNEL                                              3U   /*!< Signal channel */

/* GPIO_EMC_B2_15 (coord R4), TXEN */
/* Routed pin properties */
#define NETC_ENETC0_TXEN_PERIPHERAL                             NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_TXEN_SIGNAL                                            TX_EN   /*!< Signal name */

/* GPIO_EMC_B2_16 (coord R7), TXCLK */
/* Routed pin properties */
#define NETC_ENETC0_TXCLK_PERIPHERAL                            NETC_ENETC0_ETH4   /*!< Peripheral name */
#define NETC_ENETC0_TXCLK_SIGNAL                                          TX_CLK   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_NETC_ENETC0_ETH4_RGMII_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_EMC_B2_00 (coord N5), EMDC */
/* Routed pin properties */
#define NETC_ETH4_EMDC_PERIPHERAL                                           NETC   /*!< Peripheral name */
#define NETC_ETH4_EMDC_SIGNAL                                          netc_emdc   /*!< Signal name */

/* GPIO_EMC_B2_01 (coord R2), EMDIO */
/* Routed pin properties */
#define NETC_ETH4_EMDIO_PERIPHERAL                                          NETC   /*!< Peripheral name */
#define NETC_ETH4_EMDIO_SIGNAL                                        netc_emdio   /*!< Signal name */

/* GPIO_EMC_B2_03 (coord T5), RESET */
/* Routed pin properties */
#define NETC_ETH4_RESET_PERIPHERAL                                        RGPIO3   /*!< Peripheral name */
#define NETC_ETH4_RESET_SIGNAL                                           gpio_io   /*!< Signal name */
#define NETC_ETH4_RESET_CHANNEL                                              13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define NETC_ETH4_RESET_GPIO                                              RGPIO3   /*!< GPIO peripheral base pointer */
#define NETC_ETH4_RESET_INIT_GPIO_VALUE                                       1U   /*!< GPIO output initial state */
#define NETC_ETH4_RESET_GPIO_PIN                                             13U   /*!< GPIO pin number */
#define NETC_ETH4_RESET_GPIO_PIN_MASK                                (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_NETC_ENETC0_ETH4_PHY_Config_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_EMC_B1_02 (coord K2), RXCLK */
/* Routed pin properties */
#define NETC_SWT_ETH3_RXCLK_PERIPHERAL                             NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_RXCLK_SIGNAL                                        RX_CLK   /*!< Signal name */

/* GPIO_EMC_B1_09 (coord E1), RXD0 */
/* Routed pin properties */
#define NETC_SWT_ETH3_RXD0_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_RXD0_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_RXD0_CHANNEL                                            0U   /*!< Signal channel */

/* GPIO_EMC_B1_10 (coord E3), RXD1 */
/* Routed pin properties */
#define NETC_SWT_ETH3_RXD1_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_RXD1_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_RXD1_CHANNEL                                            1U   /*!< Signal channel */

/* GPIO_EMC_B1_04 (coord J4), RXD2 */
/* Routed pin properties */
#define NETC_SWT_ETH3_RXD2_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_RXD2_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_RXD2_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_EMC_B1_03 (coord G3), RXD3 */
/* Routed pin properties */
#define NETC_SWT_ETH3_RXD3_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_RXD3_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_RXD3_CHANNEL                                            3U   /*!< Signal channel */

/* GPIO_EMC_B1_11 (coord F2), RXEN */
/* Routed pin properties */
#define NETC_SWT_ETH3_RXEN_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_RXEN_SIGNAL                                          RX_EN   /*!< Signal name */

/* GPIO_EMC_B1_08 (coord H5), TXCLK */
/* Routed pin properties */
#define NETC_SWT_ETH3_TXCLK_PERIPHERAL                             NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_TXCLK_SIGNAL                                        TX_CLK   /*!< Signal name */

/* GPIO_EMC_B1_05 (coord H6), TXD0 */
/* Routed pin properties */
#define NETC_SWT_ETH3_TXD0_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_TXD0_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_TXD0_CHANNEL                                            0U   /*!< Signal channel */

/* GPIO_EMC_B1_06 (coord K3), TXD1 */
/* Routed pin properties */
#define NETC_SWT_ETH3_TXD1_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_TXD1_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_TXD1_CHANNEL                                            1U   /*!< Signal channel */

/* GPIO_EMC_B1_01 (coord H4), TXD2 */
/* Routed pin properties */
#define NETC_SWT_ETH3_TXD2_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_TXD2_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_TXD2_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_EMC_B1_00 (coord H3), TXD3 */
/* Routed pin properties */
#define NETC_SWT_ETH3_TXD3_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_TXD3_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH3_TXD3_CHANNEL                                            3U   /*!< Signal channel */

/* GPIO_EMC_B1_07 (coord M3), TXEN */
/* Routed pin properties */
#define NETC_SWT_ETH3_TXEN_PERIPHERAL                              NETC_SWT_ETH3   /*!< Peripheral name */
#define NETC_SWT_ETH3_TXEN_SIGNAL                                          TX_EN   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_NETC_SWT_ETH3_RGMII_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_B2_13 (coord B8), RXCLK */
/* Routed pin properties */
#define NETC_SWT_ETH2_RXCLK_PERIPHERAL                             NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_RXCLK_SIGNAL                                        RX_CLK   /*!< Signal name */

/* GPIO_B2_10 (coord A10), RXD0 */
/* Routed pin properties */
#define NETC_SWT_ETH2_RXD0_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_RXD0_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_RXD0_CHANNEL                                            0U   /*!< Signal channel */

/* GPIO_B2_11 (coord B9), RXD1 */
/* Routed pin properties */
#define NETC_SWT_ETH2_RXD1_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_RXD1_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_RXD1_CHANNEL                                            1U   /*!< Signal channel */

/* GPIO_B2_02 (coord C10), RXD2 */
/* Routed pin properties */
#define NETC_SWT_ETH2_RXD2_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_RXD2_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_RXD2_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_B2_03 (coord D9), RXD3 */
/* Routed pin properties */
#define NETC_SWT_ETH2_RXD3_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_RXD3_SIGNAL                                        RX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_RXD3_CHANNEL                                            3U   /*!< Signal channel */

/* GPIO_B2_12 (coord A8), RXEN */
/* Routed pin properties */
#define NETC_SWT_ETH2_RXEN_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_RXEN_SIGNAL                                          RX_EN   /*!< Signal name */

/* GPIO_B2_09 (coord D10), TXCLK */
/* Routed pin properties */
#define NETC_SWT_ETH2_TXCLK_PERIPHERAL                             NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_TXCLK_SIGNAL                                        TX_CLK   /*!< Signal name */

/* GPIO_B2_06 (coord E8), TXD0 */
/* Routed pin properties */
#define NETC_SWT_ETH2_TXD0_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_TXD0_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_TXD0_CHANNEL                                            0U   /*!< Signal channel */

/* GPIO_B2_07 (coord A6), TXD1 */
/* Routed pin properties */
#define NETC_SWT_ETH2_TXD1_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_TXD1_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_TXD1_CHANNEL                                            1U   /*!< Signal channel */

/* GPIO_B2_04 (coord C9), TXD2 */
/* Routed pin properties */
#define NETC_SWT_ETH2_TXD2_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_TXD2_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_TXD2_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_B2_05 (coord A9), TXD3 */
/* Routed pin properties */
#define NETC_SWT_ETH2_TXD3_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_TXD3_SIGNAL                                        TX_DATA   /*!< Signal name */
#define NETC_SWT_ETH2_TXD3_CHANNEL                                            3U   /*!< Signal channel */

/* GPIO_B2_08 (coord A7), TXEN */
/* Routed pin properties */
#define NETC_SWT_ETH2_TXEN_PERIPHERAL                              NETC_SWT_ETH2   /*!< Peripheral name */
#define NETC_SWT_ETH2_TXEN_SIGNAL                                          TX_EN   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_NETC_SWT_ETH2_RGMII_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_AD_30 (coord L17), EMDC */
/* Routed pin properties */
#define NETC_ETH2_ETH3_EMDC_PERIPHERAL                                      NETC   /*!< Peripheral name */
#define NETC_ETH2_ETH3_EMDC_SIGNAL                                     netc_emdc   /*!< Signal name */

/* GPIO_SD_B1_02 (coord D14), RESET */
/* Routed pin properties */
#define NETC_ETH2_ETH3_RESET_PERIPHERAL                                   RGPIO5   /*!< Peripheral name */
#define NETC_ETH2_ETH3_RESET_SIGNAL                                      gpio_io   /*!< Signal name */
#define NETC_ETH2_ETH3_RESET_CHANNEL                                          6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define NETC_ETH2_ETH3_RESET_GPIO                                         RGPIO5   /*!< GPIO peripheral base pointer */
#define NETC_ETH2_ETH3_RESET_INIT_GPIO_VALUE                                  0U   /*!< GPIO output initial state */
#define NETC_ETH2_ETH3_RESET_GPIO_PIN                                         6U   /*!< GPIO pin number */
#define NETC_ETH2_ETH3_RESET_GPIO_PIN_MASK                            (1U << 6U)   /*!< GPIO pin mask */

/* GPIO_AD_31 (coord K17), EMDIO */
/* Routed pin properties */
#define NETC_ETH2_ETH3_EMDIO_PERIPHERAL                                     NETC   /*!< Peripheral name */
#define NETC_ETH2_ETH3_EMDIO_SIGNAL                                   netc_emdio   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_NETC_ETH2_ETH3_PHY_Config_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_EMC_B1_09 (coord E1), RXD0 */
/* Routed pin properties */
#define ECAT_PT0_RXD0_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXD0_SIGNAL                                             PT0_RXD   /*!< Signal name */
#define ECAT_PT0_RXD0_CHANNEL                                                 0U   /*!< Signal channel */

/* GPIO_EMC_B1_10 (coord E3), RXD1 */
/* Routed pin properties */
#define ECAT_PT0_RXD1_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXD1_SIGNAL                                             PT0_RXD   /*!< Signal name */
#define ECAT_PT0_RXD1_CHANNEL                                                 1U   /*!< Signal channel */

/* GPIO_EMC_B1_04 (coord J4), RXD2 */
/* Routed pin properties */
#define ECAT_PT0_RXD2_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXD2_SIGNAL                                             PT0_RXD   /*!< Signal name */
#define ECAT_PT0_RXD2_CHANNEL                                                 2U   /*!< Signal channel */

/* GPIO_EMC_B1_03 (coord G3), RXD3 */
/* Routed pin properties */
#define ECAT_PT0_RXD3_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXD3_SIGNAL                                             PT0_RXD   /*!< Signal name */
#define ECAT_PT0_RXD3_CHANNEL                                                 3U   /*!< Signal channel */

/* GPIO_EMC_B1_02 (coord K2), RXCLK */
/* Routed pin properties */
#define ECAT_PT0_RXCLK_PERIPHERAL                                           ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXCLK_SIGNAL                                         PT0_RX_CLK   /*!< Signal name */

/* GPIO_EMC_B1_11 (coord F2), RXEN */
/* Routed pin properties */
#define ECAT_PT0_RXEN_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXEN_SIGNAL                                           PT0_RX_DV   /*!< Signal name */

/* GPIO_EMC_B1_12 (coord G6), RXER */
/* Routed pin properties */
#define ECAT_PT0_RXER_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_RXER_SIGNAL                                           PT0_RX_ER   /*!< Signal name */

/* GPIO_EMC_B1_08 (coord H5), TXCLK */
/* Routed pin properties */
#define ECAT_PT0_TXCLK_PERIPHERAL                                           ECAT   /*!< Peripheral name */
#define ECAT_PT0_TXCLK_SIGNAL                                         PT0_TX_CLK   /*!< Signal name */

/* GPIO_EMC_B1_07 (coord M3), TXEN */
/* Routed pin properties */
#define ECAT_PT0_TXEN_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_TXEN_SIGNAL                                           PT0_TX_EN   /*!< Signal name */

/* GPIO_EMC_B1_05 (coord H6), TXD0 */
/* Routed pin properties */
#define ECAT_PT0_TXD0_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_TXD0_SIGNAL                                             PT0_TXD   /*!< Signal name */
#define ECAT_PT0_TXD0_CHANNEL                                                 0U   /*!< Signal channel */

/* GPIO_EMC_B1_06 (coord K3), TXD1 */
/* Routed pin properties */
#define ECAT_PT0_TXD1_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_TXD1_SIGNAL                                             PT0_TXD   /*!< Signal name */
#define ECAT_PT0_TXD1_CHANNEL                                                 1U   /*!< Signal channel */

/* GPIO_EMC_B1_01 (coord H4), TXD2 */
/* Routed pin properties */
#define ECAT_PT0_TXD2_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_TXD2_SIGNAL                                             PT0_TXD   /*!< Signal name */
#define ECAT_PT0_TXD2_CHANNEL                                                 2U   /*!< Signal channel */

/* GPIO_EMC_B1_00 (coord H3), TXD3 */
/* Routed pin properties */
#define ECAT_PT0_TXD3_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT0_TXD3_SIGNAL                                             PT0_TXD   /*!< Signal name */
#define ECAT_PT0_TXD3_CHANNEL                                                 3U   /*!< Signal channel */

/* GPIO_AD_16 (coord N17), LINK_MII */
/* Routed pin properties */
#define ECAT_PT0_LINK_MII_PERIPHERAL                                        ECAT   /*!< Peripheral name */
#define ECAT_PT0_LINK_MII_SIGNAL                                        LINK_MII   /*!< Signal name */
#define ECAT_PT0_LINK_MII_CHANNEL                                             0U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_ECAT_PT0_MII_Pins(void);      /* Function assigned for the Cortex-M33 */

/* GPIO_B2_10 (coord A10), RXD0 */
/* Routed pin properties */
#define ECAT_PT1_RXD0_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXD0_SIGNAL                                             PT1_RXD   /*!< Signal name */
#define ECAT_PT1_RXD0_CHANNEL                                                 0U   /*!< Signal channel */

/* GPIO_B2_11 (coord B9), RXD1 */
/* Routed pin properties */
#define ECAT_PT1_RXD1_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXD1_SIGNAL                                             PT1_RXD   /*!< Signal name */
#define ECAT_PT1_RXD1_CHANNEL                                                 1U   /*!< Signal channel */

/* GPIO_B2_02 (coord C10), RXD2 */
/* Routed pin properties */
#define ECAT_PT1_RXD2_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXD2_SIGNAL                                             PT1_RXD   /*!< Signal name */
#define ECAT_PT1_RXD2_CHANNEL                                                 2U   /*!< Signal channel */

/* GPIO_B2_03 (coord D9), RXD3 */
/* Routed pin properties */
#define ECAT_PT1_RXD3_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXD3_SIGNAL                                             PT1_RXD   /*!< Signal name */
#define ECAT_PT1_RXD3_CHANNEL                                                 3U   /*!< Signal channel */

/* GPIO_B2_13 (coord B8), RXCLK */
/* Routed pin properties */
#define ECAT_PT1_RXCLK_PERIPHERAL                                           ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXCLK_SIGNAL                                         PT1_RX_CLK   /*!< Signal name */

/* GPIO_B2_12 (coord A8), RXEN */
/* Routed pin properties */
#define ECAT_PT1_RXEN_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXEN_SIGNAL                                           PT1_RX_DV   /*!< Signal name */

/* GPIO_B2_01 (coord E10), RXER */
/* Routed pin properties */
#define ECAT_PT1_RXER_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_RXER_SIGNAL                                           PT1_RX_ER   /*!< Signal name */

/* GPIO_B2_09 (coord D10), TXCLK */
/* Routed pin properties */
#define ECAT_PT1_TXCLK_PERIPHERAL                                           ECAT   /*!< Peripheral name */
#define ECAT_PT1_TXCLK_SIGNAL                                         PT1_TX_CLK   /*!< Signal name */

/* GPIO_B2_08 (coord A7), TXEN */
/* Routed pin properties */
#define ECAT_PT1_TX_EN_PERIPHERAL                                           ECAT   /*!< Peripheral name */
#define ECAT_PT1_TX_EN_SIGNAL                                          PT1_TX_EN   /*!< Signal name */

/* GPIO_B2_06 (coord E8), TXD0 */
/* Routed pin properties */
#define ECAT_PT1_TXD0_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_TXD0_SIGNAL                                             PT1_TXD   /*!< Signal name */
#define ECAT_PT1_TXD0_CHANNEL                                                 0U   /*!< Signal channel */

/* GPIO_B2_07 (coord A6), TXD1 */
/* Routed pin properties */
#define ECAT_PT1_TXD1_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_TXD1_SIGNAL                                             PT1_TXD   /*!< Signal name */
#define ECAT_PT1_TXD1_CHANNEL                                                 1U   /*!< Signal channel */

/* GPIO_B2_04 (coord C9), TXD2 */
/* Routed pin properties */
#define ECAT_PT1_TXD2_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_TXD2_SIGNAL                                             PT1_TXD   /*!< Signal name */
#define ECAT_PT1_TXD2_CHANNEL                                                 2U   /*!< Signal channel */

/* GPIO_B2_05 (coord A9), TXD3 */
/* Routed pin properties */
#define ECAT_PT1_TXD3_PERIPHERAL                                            ECAT   /*!< Peripheral name */
#define ECAT_PT1_TXD3_SIGNAL                                             PT1_TXD   /*!< Signal name */
#define ECAT_PT1_TXD3_CHANNEL                                                 3U   /*!< Signal channel */

/* GPIO_AD_17 (coord M17), LINK_MII */
/* Routed pin properties */
#define ECAT_PT1_LINK_MII_PERIPHERAL                                        ECAT   /*!< Peripheral name */
#define ECAT_PT1_LINK_MII_SIGNAL                                        LINK_MII   /*!< Signal name */
#define ECAT_PT1_LINK_MII_CHANNEL                                             1U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_ECAT_PT1_MII_Pins(void);      /* Function assigned for the Cortex-M33 */

/* GPIO_AD_30 (coord L17), EMDC */
/* Routed pin properties */
#define ECAT_PT0_PT1_EMDC_PERIPHERAL                                        ECAT   /*!< Peripheral name */
#define ECAT_PT0_PT1_EMDC_SIGNAL                                             MDC   /*!< Signal name */

/* GPIO_AD_31 (coord K17), EMDIO */
/* Routed pin properties */
#define ECAT_PT0_PT1_EMDIO_PERIPHERAL                                       ECAT   /*!< Peripheral name */
#define ECAT_PT0_PT1_EMDIO_SIGNAL                                           MDIO   /*!< Signal name */

/* GPIO_SD_B1_02 (coord D14), RESET */
/* Routed pin properties */
#define ECAT_PT0_PT1_RESET_PERIPHERAL                                     RGPIO5   /*!< Peripheral name */
#define ECAT_PT0_PT1_RESET_SIGNAL                                        gpio_io   /*!< Signal name */
#define ECAT_PT0_PT1_RESET_CHANNEL                                            6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ECAT_PT0_PT1_RESET_GPIO                                           RGPIO5   /*!< GPIO peripheral base pointer */
#define ECAT_PT0_PT1_RESET_INIT_GPIO_VALUE                                    0U   /*!< GPIO output initial state */
#define ECAT_PT0_PT1_RESET_GPIO_PIN                                           6U   /*!< GPIO pin number */
#define ECAT_PT0_PT1_RESET_GPIO_PIN_MASK                              (1U << 6U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_ECAT_PT0_PT1_PHY_Config_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_EMC_B1_39 (coord P1), FLEXSPI2_A_SS0_B */
/* Routed pin properties */
#define FLEXSPI2_A_SS0_B_PERIPHERAL                                     FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_SS0_B_SIGNAL                                  FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_EMC_B1_41 (coord R1), FLEXSPI2_A_SCLK */
/* Routed pin properties */
#define FLEXSPI2_A_SCLK_PERIPHERAL                                      FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_SCLK_SIGNAL                                    FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_EMC_B1_34 (coord L2), FLEXSPI2_B_SCLK */
/* Routed pin properties */
#define FLEXSPI2_B_SCLK_PERIPHERAL                                      FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_B_SCLK_SIGNAL                                    FLEXSPI_B_SCLK   /*!< Signal name */

/* GPIO_EMC_B1_40 (coord N2), FLEXSPI2_A_DQS */
/* Routed pin properties */
#define FLEXSPI2_A_DQS_PERIPHERAL                                       FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_DQS_SIGNAL                                      FLEXSPI_A_DQS   /*!< Signal name */

/* GPIO_EMC_B1_35 (coord L1), FLEXSPI2_A_D0 */
/* Routed pin properties */
#define FLEXSPI2_A_D0_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_D0_SIGNAL                                     FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_EMC_B1_36 (coord M1), FLEXSPI2_A_D1 */
/* Routed pin properties */
#define FLEXSPI2_A_D1_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_D1_SIGNAL                                     FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_EMC_B1_37 (coord N1), FLEXSPI2_A_D2 */
/* Routed pin properties */
#define FLEXSPI2_A_D2_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_D2_SIGNAL                                     FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_EMC_B1_38 (coord M2), FLEXSPI2_A_D3 */
/* Routed pin properties */
#define FLEXSPI2_A_D3_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_A_D3_SIGNAL                                     FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_EMC_B1_33 (coord K1), FLEXSPI2_B_D0 */
/* Routed pin properties */
#define FLEXSPI2_B_D0_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_B_D0_SIGNAL                                     FLEXSPI_B_DATA0   /*!< Signal name */

/* GPIO_EMC_B1_32 (coord J1), FLEXSPI2_B_D1 */
/* Routed pin properties */
#define FLEXSPI2_B_D1_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_B_D1_SIGNAL                                     FLEXSPI_B_DATA1   /*!< Signal name */

/* GPIO_EMC_B1_31 (coord J2), FLEXSPI2_B_D2 */
/* Routed pin properties */
#define FLEXSPI2_B_D2_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_B_D2_SIGNAL                                     FLEXSPI_B_DATA2   /*!< Signal name */

/* GPIO_EMC_B1_30 (coord H2), FLEXSPI2_B_D3 */
/* Routed pin properties */
#define FLEXSPI2_B_D3_PERIPHERAL                                        FLEXSPI2   /*!< Peripheral name */
#define FLEXSPI2_B_D3_SIGNAL                                     FLEXSPI_B_DATA3   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_FlexSPI2_HYPERRAM_Pins(void); /* Function assigned for the Cortex-M33 */

/* GPIO_AON_16 (coord C5), CAN1_TX */
/* Routed pin properties */
#define CAN1_TX_PERIPHERAL                                                  CAN1   /*!< Peripheral name */
#define CAN1_TX_SIGNAL                                                        TX   /*!< Signal name */

/* GPIO_AON_17 (coord D6), CAN1_RX */
/* Routed pin properties */
#define CAN1_RX_PERIPHERAL                                                  CAN1   /*!< Peripheral name */
#define CAN1_RX_SIGNAL                                                        RX   /*!< Signal name */

/* GPIO_AON_18 (coord E6), CAN1_STBY */
/* Routed pin properties */
#define CAN1_STBY_PERIPHERAL                                              RGPIO1   /*!< Peripheral name */
#define CAN1_STBY_SIGNAL                                                 gpio_io   /*!< Signal name */
#define CAN1_STBY_CHANNEL                                                    18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define CAN1_STBY_GPIO                                                    RGPIO1   /*!< GPIO peripheral base pointer */
#define CAN1_STBY_INIT_GPIO_VALUE                                             0U   /*!< GPIO output initial state */
#define CAN1_STBY_GPIO_PIN                                                   18U   /*!< GPIO pin number */
#define CAN1_STBY_GPIO_PIN_MASK                                      (1U << 18U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_CAN1_Pins(void);              /* Function assigned for the Cortex-M33 */

/* GPIO_AON_15 (coord B3), LED_GREEN */
/* Routed pin properties */
#define LED_GREEN_PERIPHERAL                                              RGPIO1   /*!< Peripheral name */
#define LED_GREEN_SIGNAL                                                 gpio_io   /*!< Signal name */
#define LED_GREEN_CHANNEL                                                    15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LED_GREEN_GPIO                                                    RGPIO1   /*!< GPIO peripheral base pointer */
#define LED_GREEN_INIT_GPIO_VALUE                                             0U   /*!< GPIO output initial state */
#define LED_GREEN_GPIO_PIN                                                   15U   /*!< GPIO pin number */
#define LED_GREEN_GPIO_PIN_MASK                                      (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_AON_03 (coord C8), LED_RED */
/* Routed pin properties */
#define LED_RED_PERIPHERAL                                                RGPIO1   /*!< Peripheral name */
#define LED_RED_SIGNAL                                                   gpio_io   /*!< Signal name */
#define LED_RED_CHANNEL                                                       3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LED_RED_GPIO                                                      RGPIO1   /*!< GPIO peripheral base pointer */
#define LED_RED_INIT_GPIO_VALUE                                               0U   /*!< GPIO output initial state */
#define LED_RED_GPIO_PIN                                                      3U   /*!< GPIO pin number */
#define LED_RED_GPIO_PIN_MASK                                         (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_B2_00 (coord E9), USER_BUTTON */
/* Routed pin properties */
#define USER_BUTTON_PERIPHERAL                                            RGPIO6   /*!< Peripheral name */
#define USER_BUTTON_SIGNAL                                               gpio_io   /*!< Signal name */
#define USER_BUTTON_CHANNEL                                                  14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define USER_BUTTON_GPIO                                                  RGPIO6   /*!< GPIO peripheral base pointer */
#define USER_BUTTON_GPIO_PIN                                                 14U   /*!< GPIO pin number */
#define USER_BUTTON_GPIO_PIN_MASK                                    (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_AON_10 (coord B5), LED_BLUE */
/* Routed pin properties */
#define LED_BLUE_PERIPHERAL                                               RGPIO1   /*!< Peripheral name */
#define LED_BLUE_SIGNAL                                                  gpio_io   /*!< Signal name */
#define LED_BLUE_CHANNEL                                                     10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LED_BLUE_GPIO                                                     RGPIO1   /*!< GPIO peripheral base pointer */
#define LED_BLUE_INIT_GPIO_VALUE                                              0U   /*!< GPIO output initial state */
#define LED_BLUE_GPIO_PIN                                                    10U   /*!< GPIO pin number */
#define LED_BLUE_GPIO_PIN_MASK                                       (1U << 10U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_LED_BUTTON_Pins(void);        /* Function assigned for the Cortex-M33 */

/* GPIO_B1_06 (coord B10), DIGITAL_INPUT_05 */
/* Routed pin properties */
#define DIGITAL_INPUT_05_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_05_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_05_CHANNEL                                              6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_05_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_05_GPIO_PIN                                             6U   /*!< GPIO pin number */
#define DIGITAL_INPUT_05_GPIO_PIN_MASK                                (1U << 6U)   /*!< GPIO pin mask */

/* GPIO_B1_07 (coord D13), DIGITAL_INPUT_03 */
/* Routed pin properties */
#define DIGITAL_INPUT_03_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_03_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_03_CHANNEL                                              7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_03_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_03_GPIO_PIN                                             7U   /*!< GPIO pin number */
#define DIGITAL_INPUT_03_GPIO_PIN_MASK                                (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_B1_08 (coord B14), DIGITAL_INPUT_02 */
/* Routed pin properties */
#define DIGITAL_INPUT_02_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_02_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_02_CHANNEL                                              8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_02_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_02_GPIO_PIN                                             8U   /*!< GPIO pin number */
#define DIGITAL_INPUT_02_GPIO_PIN_MASK                                (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_B1_09 (coord A15), DIGITAL_INPUT_06 */
/* Routed pin properties */
#define DIGITAL_INPUT_06_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_06_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_06_CHANNEL                                              9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_06_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_06_GPIO_PIN                                             9U   /*!< GPIO pin number */
#define DIGITAL_INPUT_06_GPIO_PIN_MASK                                (1U << 9U)   /*!< GPIO pin mask */

/* GPIO_B1_10 (coord A13), DIGITAL_INPUT_07 */
/* Routed pin properties */
#define DIGITAL_INPUT_07_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_07_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_07_CHANNEL                                             10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_07_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_07_GPIO_PIN                                            10U   /*!< GPIO pin number */
#define DIGITAL_INPUT_07_GPIO_PIN_MASK                               (1U << 10U)   /*!< GPIO pin mask */

/* GPIO_B1_12 (coord A11), DIGITAL_INPUT_01 */
/* Routed pin properties */
#define DIGITAL_INPUT_01_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_01_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_01_CHANNEL                                             12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_01_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_01_GPIO_PIN                                            12U   /*!< GPIO pin number */
#define DIGITAL_INPUT_01_GPIO_PIN_MASK                               (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_B1_13 (coord B11), DIGITAL_INPUT_04 */
/* Routed pin properties */
#define DIGITAL_INPUT_04_PERIPHERAL                                       RGPIO6   /*!< Peripheral name */
#define DIGITAL_INPUT_04_SIGNAL                                          gpio_io   /*!< Signal name */
#define DIGITAL_INPUT_04_CHANNEL                                             13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_INPUT_04_GPIO                                             RGPIO6   /*!< GPIO peripheral base pointer */
#define DIGITAL_INPUT_04_GPIO_PIN                                            13U   /*!< GPIO pin number */
#define DIGITAL_INPUT_04_GPIO_PIN_MASK                               (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_Digital_Input_Pins(void);     /* Function assigned for the Cortex-M33 */

/* GPIO_EMC_B1_21 (coord K4), DIGITAL_OUTPUT_01 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_01_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_01_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_01_CHANNEL                                            21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_01_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_01_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_01_GPIO_PIN                                           21U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_01_GPIO_PIN_MASK                              (1U << 21U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_22 (coord L3), DIGITAL_OUTPUT_02 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_02_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_02_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_02_CHANNEL                                            22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_02_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_02_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_02_GPIO_PIN                                           22U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_02_GPIO_PIN_MASK                              (1U << 22U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_23 (coord F1), DIGITAL_OUTPUT_03 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_03_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_03_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_03_CHANNEL                                            23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_03_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_03_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_03_GPIO_PIN                                           23U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_03_GPIO_PIN_MASK                              (1U << 23U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_24 (coord P2), DIGITAL_OUTPUT_04 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_04_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_04_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_04_CHANNEL                                            24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_04_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_04_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_04_GPIO_PIN                                           24U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_04_GPIO_PIN_MASK                              (1U << 24U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_25 (coord N3), DIGITAL_OUTPUT_05 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_05_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_05_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_05_CHANNEL                                            25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_05_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_05_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_05_GPIO_PIN                                           25U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_05_GPIO_PIN_MASK                              (1U << 25U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_26 (coord N4), DIGITAL_OUTPUT_06 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_06_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_06_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_06_CHANNEL                                            26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_06_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_06_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_06_GPIO_PIN                                           26U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_06_GPIO_PIN_MASK                              (1U << 26U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_27 (coord J3), DIGITAL_OUTPUT_07 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_07_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_07_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_07_CHANNEL                                            27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_07_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_07_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_07_GPIO_PIN                                           27U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_07_GPIO_PIN_MASK                              (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_28 (coord F5), DIGITAL_OUTPUT_08 */
/* Routed pin properties */
#define DIGITAL_OUTPUT_08_PERIPHERAL                                      RGPIO2   /*!< Peripheral name */
#define DIGITAL_OUTPUT_08_SIGNAL                                         gpio_io   /*!< Signal name */
#define DIGITAL_OUTPUT_08_CHANNEL                                            28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define DIGITAL_OUTPUT_08_GPIO                                            RGPIO2   /*!< GPIO peripheral base pointer */
#define DIGITAL_OUTPUT_08_INIT_GPIO_VALUE                                     0U   /*!< GPIO output initial state */
#define DIGITAL_OUTPUT_08_GPIO_PIN                                           28U   /*!< GPIO pin number */
#define DIGITAL_OUTPUT_08_GPIO_PIN_MASK                              (1U << 28U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_Digital_Output_Pins(void);    /* Function assigned for the Cortex-M33 */

/* GPIO_AON_05 (coord C7), GPIO1_IO5 */
/* Routed pin properties */
#define AFE_CS_PERIPHERAL                                                 RGPIO1   /*!< Peripheral name */
#define AFE_CS_SIGNAL                                                    gpio_io   /*!< Signal name */
#define AFE_CS_CHANNEL                                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define AFE_CS_GPIO                                                       RGPIO1   /*!< GPIO peripheral base pointer */
#define AFE_CS_INIT_GPIO_VALUE                                                1U   /*!< GPIO output initial state */
#define AFE_CS_GPIO_PIN                                                       5U   /*!< GPIO pin number */
#define AFE_CS_GPIO_PIN_MASK                                          (1U << 5U)   /*!< GPIO pin mask */

/* GPIO_AON_04 (coord B4), LPSPI1_SCK */
/* Routed pin properties */
#define AFE_SPI_SCK_PERIPHERAL                                            LPSPI1   /*!< Peripheral name */
#define AFE_SPI_SCK_SIGNAL                                                   SCK   /*!< Signal name */

/* GPIO_AON_06 (coord E7), LPSPI1_SDO */
/* Routed pin properties */
#define AFE_SPI_MOSI_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define AFE_SPI_MOSI_SIGNAL                                                 SOUT   /*!< Signal name */

/* GPIO_AON_07 (coord C6), LPSPI1_SDI */
/* Routed pin properties */
#define AFE_SPI_MISO_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define AFE_SPI_MISO_SIGNAL                                                  SIN   /*!< Signal name */

/* GPIO_AD_15 (coord N16), GPIO4_IO15 */
/* Routed pin properties */
#define AFE_DRDY_PERIPHERAL                                               RGPIO4   /*!< Peripheral name */
#define AFE_DRDY_SIGNAL                                                  gpio_io   /*!< Signal name */
#define AFE_DRDY_CHANNEL                                                     15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define AFE_DRDY_GPIO                                                     RGPIO4   /*!< GPIO peripheral base pointer */
#define AFE_DRDY_GPIO_PIN                                                    15U   /*!< GPIO pin number */
#define AFE_DRDY_GPIO_PIN_MASK                                       (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_04 (coord B15), GPIO5_IO8 */
/* Routed pin properties */
#define AFE_RST_PERIPHERAL                                                RGPIO5   /*!< Peripheral name */
#define AFE_RST_SIGNAL                                                   gpio_io   /*!< Signal name */
#define AFE_RST_CHANNEL                                                       8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define AFE_RST_GPIO                                                      RGPIO5   /*!< GPIO peripheral base pointer */
#define AFE_RST_INIT_GPIO_VALUE                                               0U   /*!< GPIO output initial state */
#define AFE_RST_GPIO_PIN                                                      8U   /*!< GPIO pin number */
#define AFE_RST_GPIO_PIN_MASK                                         (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_03 (coord C15), GPIO5_IO7 */
/* Routed pin properties */
#define AFE_SYNC_PERIPHERAL                                               RGPIO5   /*!< Peripheral name */
#define AFE_SYNC_SIGNAL                                                  gpio_io   /*!< Signal name */
#define AFE_SYNC_CHANNEL                                                      7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define AFE_SYNC_GPIO                                                     RGPIO5   /*!< GPIO peripheral base pointer */
#define AFE_SYNC_INIT_GPIO_VALUE                                              0U   /*!< GPIO output initial state */
#define AFE_SYNC_GPIO_PIN                                                     7U   /*!< GPIO pin number */
#define AFE_SYNC_GPIO_PIN_MASK                                        (1U << 7U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_AFE_Pins(void);               /* Function assigned for the Cortex-M33 */

/* GPIO_AD_26 (coord M14), FLEXPWM_2_1A */
/* Routed pin properties */
#define FLEXPWM_2_1A_PERIPHERAL                                             PWM2   /*!< Peripheral name */
#define FLEXPWM_2_1A_SIGNAL                                                    A   /*!< Signal name */
#define FLEXPWM_2_1A_CHANNEL                                                  1U   /*!< Signal channel */

/* GPIO_AD_27 (coord M16), FLEXPWM_2_1B */
/* Routed pin properties */
#define FLEXPWM_2_1B_PERIPHERAL                                             PWM2   /*!< Peripheral name */
#define FLEXPWM_2_1B_SIGNAL                                                    B   /*!< Signal name */
#define FLEXPWM_2_1B_CHANNEL                                                  1U   /*!< Signal channel */

/* GPIO_AD_28 (coord L16), FLEXPWM_2_2B */
/* Routed pin properties */
#define FLEXPWM_2_2B_PERIPHERAL                                             PWM2   /*!< Peripheral name */
#define FLEXPWM_2_2B_SIGNAL                                                    B   /*!< Signal name */
#define FLEXPWM_2_2B_CHANNEL                                                  2U   /*!< Signal channel */

/* GPIO_AD_29 (coord L15), FLEXPWM_2_2A */
/* Routed pin properties */
#define FLEXPWM_2_2A_PERIPHERAL                                             PWM2   /*!< Peripheral name */
#define FLEXPWM_2_2A_SIGNAL                                                    A   /*!< Signal name */
#define FLEXPWM_2_2A_CHANNEL                                                  2U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_PWM_Pins(void);               /* Function assigned for the Cortex-M33 */

/* GPIO_AD_18 (coord K16), ECAT_SCL */
/* Routed pin properties */
#define ECAT_SCL_PERIPHERAL                                                 ECAT   /*!< Peripheral name */
#define ECAT_SCL_SIGNAL                                                      SCL   /*!< Signal name */

/* GPIO_AD_19 (coord L13), ECAT_SDA */
/* Routed pin properties */
#define ECAT_SDA_PERIPHERAL                                                 ECAT   /*!< Peripheral name */
#define ECAT_SDA_SIGNAL                                                      SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_ECAT_I2C_Pins(void);          /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
